### ISSUE TITLE
Session management (for data logging, naming beers, etc)

### ISSUE THREAD

**Issue by elcojacobs** [BrewBlox/brewblox-devcon-spark#164]
From a discussion with Guillaume:
- We want to see remotely what the currently controlled beer is (batch name/number)
- We want data logging to have 'batches', so we can fetch data of a specific beer

It occurred to me that we could use the existing profiles functionality that's already in the firmware for this.
- Each block already belongs to one or more profiles. 
- It makes sense that stopping a session equals deactivating a profile.
- It makes sense that renaming a profile equals a new session (the collection of blocks is now working on a new process)
- We can tag all data going into influx with the profiles the block belonged to (string name). This can be used later to fetch all data of a certain batch by tag. The devcon service has all the info it needs and doesn't need to be aware of dates.
- By renaming a profile, you can start a new batch (with the same block config).

Probably these changes are also needed to implement this:
- Move system blocks to a system profile.
- Rename 'profile' to something else, like 'collection, group'
- On the LCD display, show active profiles on the bottom (name). We can store the string names in the firmware too then instead of datastore.

Possible UI improvements to accompany this:
- Filter blocks by profile
- Display graphs of a tag instead of a time range
- Some more intuitive interface to use profiles as batches
- Renaming tags in influx (for a time range) in case you forgot to start your session.
- We could have a special tag/profile name for 'keep the blocks active, but no data logging'.

**Comment by steersbob** [comment]
Given how this issue requires changes in UI, devcon, history, and firmware, it is now split in separate issues.
